### ISSUE TITLE
Publish Invidious Config

### ISSUE THREAD

**Issue by RiversideRocks** [silkkycloud/silkky.cloud#1]
If possible, could you publish your config.yml file?

**Comment by TheSilkky** [comment]
```yml
environment:
  INVIDIOUS_CONFIG: |
    channel_threads: 1
    feed_threads: 1
    check_tables: true
    db:
      user: kemal   
      password: ${DATABASE_PASSWORD}  
      host: database          
      port: 5432 
      dbname: invidious        
    full_refresh: false        
    popular_enabled: true        
    login_enabled: true        
    registration_enabled: true        
    statistics_enabled: true        
    admin_email: ${ADMIN_MAIL}        
    https_only: true        
    external_port: 443        
    domain: ${INVIDIOUS_HOSTNAME}        
    captcha_key: ${ANTI_KEY}        
    banner: "Support this instance: https://silkky.cloud/contribute#Donate"
```
My full configuration is here: https://github.com/silkkycloud/invidious.

I’m redesigning the website to include a lot of resources, guides etc. I’ll publish all my configs there.
